# Generated by Django 4.1 on 2022-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="image",
            field=models.ImageField(default="avatar.svg", upload_to=""),
        ),
    ]
