# Generated by Django 4.1 on 2022-09-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_lesson_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(default="avatar.svg", upload_to=""),
        ),
    ]
