# Generated by Django 4.1 on 2022-09-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="image",
            field=models.ImageField(default="avatar.svg", upload_to=""),
        ),
    ]
