# Generated by Django 4.1 on 2022-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
